# Generated by Django 5.2.13 on 2026-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_ciclo_credito_pedido_clave_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('mercadopago', 'MercadoPago (simulado)'), ('transferencia', 'Transferencia bancaria'), ('credito_comercial', 'Credito comercial'), ('solicitud_credito', 'Solicitud de crédito')], default='transferencia', max_length=25),
        ),
    ]
