# Generated by Django 6.0.4 on 2026-04-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_credito_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_proveedor', to='plataforma.pedido')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to='plataforma.proveedor')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to='plataforma.tecnico')),
            ],
            options={
                'verbose_name': 'Calificación Proveedor',
                'verbose_name_plural': 'Calificaciones Proveedores',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('tecnico', 'pedido')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntualidad', models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('trato', models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('comentario_privado', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_tecnico', to='plataforma.pedido')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to='plataforma.proveedor')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to='plataforma.tecnico')),
            ],
            options={
                'verbose_name': 'Calificación Técnico',
                'verbose_name_plural': 'Calificaciones Técnicos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('proveedor', 'pedido')},
            },
        ),
    ]
