# Generated by Django 6.0.4 on 2026-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_calificacionproveedor_calificaciontecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='cuit',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
