# Generated by Django 5.2.13 on 2026-05-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_proveedor_cuit_proveedor_is_approved_tecnico_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='horarios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/imagenes/'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/logos/'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nota_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='nota_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
