# Generated by Django 5.2.13 on 2026-05-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_proveedor_estado_proveedor_horarios_proveedor_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
