# Generated by Django 5.2.13 on 2026-05-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_producto_modelo_producto_stock_proveedor_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
