# Generated by Django 5.2.13 on 2026-05-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='respuesta_proveedor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
