# Generated by Django 5.2.13 on 2026-05-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_add_respuesta_proveedor_to_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('mecanica_automotriz', 'Mecánica Automotriz'), ('tecnico_computadoras', 'Técnico de Computadoras')], max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(choices=[('mecanica_automotriz', 'Mecánica Automotriz'), ('tecnico_computadoras', 'Técnico de Computadoras')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='especialidad',
            field=models.CharField(choices=[('mecanica_automotriz', 'Mecánica Automotriz'), ('tecnico_computadoras', 'Técnico de Computadoras')], max_length=100),
        ),
    ]
