# Generated by Django 5.2.13 on 2026-06-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_tecnico_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
