# Generated by Django 5.2.13 on 2026-06-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_pedido_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_transferencia',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_transferencia/'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='alias_transferencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco_transferencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cbu_transferencia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='titular_transferencia',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
