# Generated by Django 5.2.13 on 2026-08-10 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('nombre_negocio', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('rubro', models.CharField(choices=[('mecanica_automotriz', 'Mecánica Automotriz'), ('tecnico_computadoras', 'Técnico de Computadoras')], max_length=100)),
                ('horarios', models.CharField(blank=True, max_length=200)),
                ('banco_transferencia', models.CharField(blank=True, max_length=100)),
                ('titular_transferencia', models.CharField(blank=True, max_length=150)),
                ('cbu_transferencia', models.CharField(blank=True, max_length=30)),
                ('alias_transferencia', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='proveedores/logos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proveedores/imagenes/')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=15)),
                ('nota_admin', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('especialidad', models.CharField(choices=[('mecanica_automotriz', 'Mecánica Automotriz'), ('tecnico_computadoras', 'Técnico de Computadoras')], max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=15)),
                ('nota_admin', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
    ]
