# Generated by Django 5.2.13 on 2026-09-17 12:31

import apps.usuarios.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaModeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.TextField()),
                ('texto', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_moderacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ImagenModeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=5)),
                ('imagen', models.ImageField(storage=apps.usuarios.storage.almacenamiento_moderacion, upload_to=apps.usuarios.storage.ruta_imagen_moderacion)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='usuarios.respuestamoderacion')),
            ],
        ),
    ]
