# Generated by Django 5.2.13 on 2026-09-07 13:55

from django.db import migrations, models


def separar_creditos_sin_deuda(apps, schema_editor):
    # Todo pedido anterior de estos creditos ya esta saldado. Los saldos
    # positivos no permiten inferir que pedidos historicos fueron pagados.
    Credito = apps.get_model('creditos', 'Credito')
    Credito.objects.using(schema_editor.connection.alias).filter(
        saldo_usado=0,
    ).update(ciclo=1)


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
        ('core', '0001_import_legacy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='ciclo',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(separar_creditos_sin_deuda, migrations.RunPython.noop),
    ]
