from .auth import (
    dashboard,
    editar_perfil,
    espera_aprobacion,
    inicio,
    login_view,
    logout_view,
    perfil_proveedor,
    perfil_tecnico,
    registro_proveedor,
    registro_tecnico,
    registro_tipo,
)
from .calificaciones import calificar_proveedor, calificar_tecnico
from .catalogo import (
    agregar_producto,
    catalogo_proveedor,
    editar_producto,
    eliminar_producto,
    toggle_disponibilidad,
)
from .creditos import (
    asignar_credito,
    deudas_tecnicos,
    detalle_deuda_tecnico,
    gestionar_creditos_proveedor,
    marcar_deuda_saldada,
    mis_creditos,
    revocar_credito,
)
from .moderacion import (
    aprobar_usuario,
    panel_moderacion,
    rechazar_usuario,
    solicitar_info,
    suspender_usuario,
)
from .pedidos import (
    cancelar_pedido,
    completar_pedido,
    crear_pedido,
    detalle_pedido_proveedor,
    exportar_historial,
    gestionar_pedido,
    mis_pedidos,
    pedidos_recibidos,
)
from .search import buscar_repuestos

__all__ = [
    'agregar_producto',
    'aprobar_usuario',
    'asignar_credito',
    'buscar_repuestos',
    'calificar_proveedor',
    'calificar_tecnico',
    'cancelar_pedido',
    'catalogo_proveedor',
    'completar_pedido',
    'crear_pedido',
    'dashboard',
    'deudas_tecnicos',
    'detalle_deuda_tecnico',
    'detalle_pedido_proveedor',
    'editar_perfil',
    'editar_producto',
    'eliminar_producto',
    'espera_aprobacion',
    'exportar_historial',
    'gestionar_creditos_proveedor',
    'gestionar_pedido',
    'inicio',
    'login_view',
    'logout_view',
    'marcar_deuda_saldada',
    'mis_creditos',
    'mis_pedidos',
    'panel_moderacion',
    'pedidos_recibidos',
    'perfil_proveedor',
    'perfil_tecnico',
    'rechazar_usuario',
    'registro_proveedor',
    'registro_tecnico',
    'registro_tipo',
    'revocar_credito',
    'solicitar_info',
    'suspender_usuario',
    'toggle_disponibilidad',
]
